# Assignment 1

# Numpy

In [143]:
import numpy as np

## 1. Create numpy arrays

### 1.

In [144]:
x = [1,2,3]
x = np.array(x)
print(x)

[1 2 3]


### 2.

In [145]:
x = 6 * np.ones((3,2))
print(x)

[[6. 6.]
 [6. 6.]
 [6. 6.]]


In [146]:
x = np.full((3,2), 6)
print(x)

[[6 6]
 [6 6]
 [6 6]]


### 3

In [147]:
x = np.arange(start = 2, stop = 101, step = 2)
avg = np.mean(x)
print(avg)

51.0


### 4

In [148]:
np.random.seed(0)
x = np.random.random((3,3,3))
print(x)

[[[0.5488135  0.71518937 0.60276338]
  [0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276]]

 [[0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606]
  [0.0871293  0.0202184  0.83261985]]

 [[0.77815675 0.87001215 0.97861834]
  [0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329]]]


### 5

In [149]:
x = np.arange(10,22)
x = np.reshape(x,(3,4))
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 6

In [150]:
x = 5 * np.ones(10)
for i in range(1,10):
    x[i] = x[i-1] + 3
print(x)

[ 5.  8. 11. 14. 17. 20. 23. 26. 29. 32.]


In [151]:
x = np.arange(5,35,3)
print(x)

[ 5  8 11 14 17 20 23 26 29 32]


### 7

In [152]:
np.random.seed(0)
x = np.random.random((10,10))
print("total size " + str(x.nbytes) + " bytes")

total size 800 bytes


### 8

In [153]:
x = np.zeros(10)
x[:] = np.NaN
x[4] = 1
print(x)

[nan nan nan nan  1. nan nan nan nan nan]


### 9

In [154]:
x = np.arange(10, 50)
x = np.flip(x)
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 10

In [155]:
np.random.seed(0)
x = np.random.random((3,2))
print(x)

#As long as the seed is set we can get the same value in next iteration

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]


### 11

In [156]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 12

In [157]:
x = np.ones((5,5))
x = np.pad(x, 1)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 13

In [158]:
x = np.arange(1,6)
x = np.diag(x)
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### 14

In [159]:
x = np.arange(5)
x = np.tile(x, (5,1))
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 15

In [160]:
np.random.seed(0)
x = np.random.randint(100, size=(1,10))
x = np.sort(x)
print(x)

[[ 9 21 36 44 47 64 67 67 83 87]]


## 2. Operations on numpy arrays

### 1.

In [161]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
count = np.cumsum(x == 1)
index = np.searchsorted(count, 5)
print(index)

8


### 2.

In [162]:
x = np.arange(1,10)
a,b,c = np.split(x,[4,6])
print(a, b, c)

[1 2 3 4] [5 6] [7 8 9]


### 3.

In [163]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [164]:
y = np.split(x, 2, 1)
print(y)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### 4.

In [165]:
x = np.arange(5, 50, 5).reshape(3,3)
print(x[:2, 1:])

[[10 15]
 [25 30]]


In [166]:
print(x[1,0])

20


### 5.

In [167]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
print(np.concatenate([x,y],axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 6.

In [168]:
np.random.seed(0)
x = np.random.randint(10, size=(5,3))
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [169]:
min = np.min(x, axis=1) # row
max = np.max(x, axis=1)
print(min, max)


[0 3 2 4 1] [5 9 5 7 8]


In [170]:
print(min/max)

[0.         0.33333333 0.4        0.57142857 0.125     ]


### 7.

In [171]:
np.random.seed(0)
x = np.random.randint(10,size=(5,5))
print(np.mean(x),np.std(x))
print(x)
from sklearn import preprocessing
print(preprocessing.normalize(x))

5.4 2.6683328128252666
[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
[[0.52128604 0.         0.31277162 0.31277162 0.72980045]
 [0.77459667 0.25819889 0.43033148 0.17213259 0.34426519]
 [0.47851015 0.41015156 0.54686874 0.54686874 0.06835859]
 [0.42532872 0.49621684 0.49621684 0.56710496 0.07088812]
 [0.30599503 0.55079106 0.48959205 0.55079106 0.24479602]]


In [172]:
row_sums = x.sum(axis=1)
y = x / row_sums[:, np.newaxis]
y

array([[0.27777778, 0.        , 0.16666667, 0.16666667, 0.38888889],
       [0.39130435, 0.13043478, 0.2173913 , 0.08695652, 0.17391304],
       [0.23333333, 0.2       , 0.26666667, 0.26666667, 0.03333333],
       [0.20689655, 0.24137931, 0.24137931, 0.27586207, 0.03448276],
       [0.14285714, 0.25714286, 0.22857143, 0.25714286, 0.11428571]])

In [173]:
y = x - np.mean(x)
y = y/np.std(x)
y

array([[-0.14990634, -2.02373556, -0.89943803, -0.89943803,  0.59962535],
       [ 1.34915704, -0.89943803, -0.14990634, -1.27420387, -0.52467218],
       [ 0.59962535,  0.22485951,  0.9743912 ,  0.9743912 , -1.64896972],
       [ 0.22485951,  0.59962535,  0.59962535,  0.9743912 , -1.64896972],
       [-0.14990634,  1.34915704,  0.9743912 ,  1.34915704, -0.52467218]])

### 8.

In [174]:
x = np.arange(0,3)
y = np.arange(3,7)
z = np.arange(7,10)
np.concatenate([x,y,z])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 9.

In [175]:
np.random.seed(0)
x = np.random.randint(100, size=(1,20))
x

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65,
        39, 87, 46, 88]])

In [176]:
result_index = []
result_value = []
x = x[0]
for i in range(len(x)):
    if (x[i] <= 55 and x[i] >= 15):
        result_index.append(i)
        result_value.append(x[i])
    
print("result_index = ", result_index)
print("result_value = ",result_value)
#Alternative
x1 = np.where(np.logical_and(x>=15, x<=55))
x1

result_index =  [0, 1, 7, 8, 16, 18]
result_value =  [44, 47, 21, 36, 39, 46]


(array([ 0,  1,  7,  8, 16, 18], dtype=int64),)

### 10.

In [177]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


### 11.

In [178]:
x = np.arange(21)
np.where(x%2 == 1, -1, x)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20])

### 12.

In [179]:
np.random.seed(0)
x = np.random.randint(100, size = (1,10))
print(x)

[[44 47 64 67 67  9 83 21 36 87]]


In [180]:
np.random.seed(1)
y = np.random.randint(100, size=(1,10))
print(y)

[[37 12 72  9 75  5 79 64 16  1]]


In [181]:
%timeit np.sum(x)

4.25 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [182]:
%timeit np.sum(y)

4.23 µs ± 419 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [183]:
%timeit np.cumsum(x)[-1]

2.7 µs ± 214 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [184]:
%timeit np.nansum(x)

5.98 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [185]:
x = np.array(x[0])

In [186]:
%timeit sum(x)

2.47 µs ± 47.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 13.

In [187]:
np.random.seed(0)
x = np.zeros((10,10))
y = np.random.randint(100, size=(1,3))
y = y[0] # indexes to replace
y

array([44, 47, 64])

In [188]:
x = np.reshape(x, (1,100)) # make original array as 1D
np.put(x, y, y) # replace indexes with the same index value
x = x.reshape(10,10) # reshape into original 10x10 format
x

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 44.,  0.,  0., 47.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 64.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

### 14.

In [189]:
np.random.seed(0)
x = np.random.randint(100, size=(5,10))
x

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58, 65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72,  9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74, 23, 35]])

In [190]:
mean = np.mean(x, axis=1)
mean

array([52.5, 64.1, 54.9, 51. , 39.7])

In [191]:
x = x - x.mean(axis=1, keepdims = True)
print(x)

[[ -8.5  -5.5  11.5  14.5  14.5 -43.5  30.5 -31.5 -16.5  34.5]
 [  5.9  23.9  23.9 -52.1  -6.1   0.9 -25.1  22.9 -18.1  23.9]
 [ 26.1 -17.9 -29.9  22.1  17.1 -45.9 -34.9  25.1  14.1  24.1]
 [ -4.   13.   31.   48.   37.   -2.  -22.  -32.  -32.  -37. ]
 [ -0.7  -7.7  25.3 -30.7  17.3  -7.7  -8.7  34.3 -16.7  -4.7]]


# 3. Indexing and slicing

In [192]:
x = [ 3, 6, 9, 25, 10, 8] 

### 1.1

In [193]:
x[1:]

[6, 9, 25, 10, 8]

### 1.2

In [194]:
x[:-1]

[3, 6, 9, 25, 10]

### 1.3

In [195]:
x[::2]

[3, 9, 10]

### 1.4

In [196]:
np.flip(x)

array([ 8, 10, 25,  9,  6,  3])

### 2. Multidimensional arrays

### 2.1

In [197]:
x = np.arange(32).reshape(8,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### 2.2

In [198]:
x[0,2] = 0
print(x)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### 2.3

In [199]:
print(x[:, 1]) # indexing starts from 0

[ 1  5  9 13 17 21 25 29]


### 2.4

In [200]:
x = np.array([[ 9, 10, 11],
 [13, 14, 15],
 [17, 18, 19]])

In [201]:
x[:3, :3]

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

### 3.

In [202]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [203]:
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


# 4. Broadcasting

### 4.1

In [204]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [205]:
print(a_2d - b_1d.reshape(3,1))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


### 4.2

In [206]:
x = np.arange(1,7).reshape(6,1)
y = np.arange(1,7).reshape(1,6)
print(x * y)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [207]:
x = [[0] * 6 for i in range(6)]
for i in range(1,7):
    for j in range(1,7):
        x[i-1][j-1] = i * j
print(x)

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [3, 6, 9, 12, 15, 18], [4, 8, 12, 16, 20, 24], [5, 10, 15, 20, 25, 30], [6, 12, 18, 24, 30, 36]]
